version: '3.8'

services:
  
  ikal-game:
    image: docker.jesusyaro.com/ikal
    build:
      context: .
      dockerfile: ./phaser-angular-app/Dockerfile
    container_name: ikal
    ports:
      - '80:80'
    volumes:
      - ./phaser-angular-app:/usr/src/app
    stdin_open: true
